analysisProfiles:
  # scen: "" (all scenarios)
  all-quick:
    scen: ""
    timeoutRec: 5
    timeoutRep: 5
    keepTrace: false
    stats: true
    time: true

  all-default:
    scen: ""
    timeoutRec: 20
    timeoutRep: 20
    keepTrace: true
    stats: true
    time: true

  all-deep:
    scen: ""
    timeoutRec: 60
    timeoutRep: 60
    keepTrace: true
    stats: true
    time: true

  # scen: "m" (mixed deadlocks)
  mixed-quick:
    scen: "m"
    timeoutRec: 5
    timeoutRep: 5
    keepTrace: false
    stats: true
    time: true

  mixed-default:
    scen: "m"
    timeoutRec: 20
    timeoutRep: 20
    keepTrace: true
    stats: true
    time: true

  mixed-deep:
    scen: "m"
    timeoutRec: 150
    timeoutRep: 150
    keepTrace: true
    stats: true
    time: true

  # scen: "mc" (blocking / channel+lock)
  block-quick:
    scen: "mc"
    timeoutRec: 5
    timeoutRep: 5
    keepTrace: false
    stats: true
    time: true

  block-default:
    scen: "mc"
    timeoutRec: 20
    timeoutRep: 20
    keepTrace: true
    stats: true
    time: true

  block-deep:
    scen: "mc"
    timeoutRec: 60
    timeoutRep: 60
    keepTrace: true
    stats: true
    time: true

  # scen: "c" (cyclic)
  cyclic-quick:
    scen: "c"
    timeoutRec: 5
    timeoutRep: 5
    keepTrace: false
    stats: true
    time: true

  cyclic-default:
    scen: "c"
    timeoutRec: 20
    timeoutRep: 20
    keepTrace: true
    stats: true
    time: true

  cyclic-deep:
    scen: "c"
    timeoutRec: 60
    timeoutRep: 60
    keepTrace: true
    stats: true
    time: true

fuzzProfiles:
  quick:
    maxRuns: 10
    timeoutFuz: 5
    timeoutRec: 5
    timeoutRep: 5
    keepTrace: false
    stats: true
    time: true

  default:
    maxRuns: 50
    timeoutFuz: 10
    timeoutRec: 20
    timeoutRep: 20
    keepTrace: true
    stats: true
    time: true

  deep:
    maxRuns: 200
    timeoutFuz: 30
    timeoutRec: 60
    timeoutRep: 60
    keepTrace: true
    stats: true
    time: true